### PR TITLE
Fix deposit TX's effectiveGasPrice

### LINKED ISSUE #159: Incorrect effectiveGasPrice in receipt
`erigon version 0.05.0-2.55.1`

On Optimism Mainnet the following transaction has the incorrect "effectiveGasPrice"

```json
{"jsonrpc":"2.0","id":1,"method":"eth_getTransactionReceipt","params":["0xd8fca681d83ef12ebf44a31dafad3431b5cfcb8f7490851c8d4337085a99a38d"]}
```

Op-Erigon is returning: `"effectiveGasPrice": "0x3d7b56f"`

Op-Geth is returning: `"effectiveGasPrice": "0x0",`

Based on the explanation from the Optimism team:
> it was a deposit-transaction (i.e. no signature, generated by system as part of upgrade), so no gas is paid in L2, and so the price should be 0 [...] op-erigon for some reason implies that deposits pay gas on L2, whereas they don't. Likely some receipt-hydration quirk/bug.

I don't have any nodes on `v2.56.2-0.5.0` to test with right now but I'll try to report back, if anyone can confirm that would be 🙏

### PR DESCRIPTION
**Pull request by mininny**
Resolves #159 

Deposit Tx's have fixed effective gas price of 0, but existing op-erigon code calculates deposit tx's gas price with baseFee. 
This PR sets the effectiveGasPrice to `tx.GetPrice()` which is always 0 for DepositTx. 

op-geth reference: https://github.com/ethereum-optimism/op-geth/blob/da6ea729b858ce854ed4c3dd0979eae0855790c0/core/types/deposit_tx.go#L83-L85

---
Example Result
AS-IS:
```
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x2a4fcbf27eeba8dbcc6fdaa3d00ecd1b600ee530af5390ee98d8c4019df3f524",..."effectiveGasPrice":"0xfc"...}
```
TO-BE:
```
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x2a4fcbf27eeba8dbcc6fdaa3d00ecd1b600ee530af5390ee98d8c4019df3f524"..."effectiveGasPrice":"0x0"...}
```

### CODE REVIEW

File: core/types/deposit_tx.go [hunk 1]
```diff
@@ -380,23 +380,8 @@ func (tx DepositTx) IsStarkNet() bool {
 func (tx DepositTx) GetPrice() *uint256.Int  { return uint256.NewInt(0) }
 func (tx DepositTx) GetTip() *uint256.Int    { return uint256.NewInt(0) }
 func (tx DepositTx) GetFeeCap() *uint256.Int { return uint256.NewInt(0) }
-
-// Is this needed at all?
```
Comment (mininny) [inline core/types/deposit_tx.go:384]: This is unused and effectively useless.

**Comment by ImTei** [comment]
`effectiveGasPrice()` of op-geth seems to be used only for making receipts, but op-erigon's `GetEffectiveGasTip()` is used in more cases. I wonder if these changes are suitable for all cases. Can you confirm?

**Comment by mininny** [comment]
> `effectiveGasPrice()` of op-geth seems to be used only for making receipts, but op-erigon's `GetEffectiveGasTip()` is used in more cases. I wonder if these changes are suitable for all cases. Can you confirm?

@ImTei 
The changes have no effect because `GetTip()` and `GetFeeCap()` has a fixed value of 0 already and always returns 0 in all code path of `GetEffectiveGasTip()`. 👍

**Review by ImTei — APPROVED** [review]
